matrix:
  include:
    
    # Windows MSVC x64 Vulkan 1.0
    - os: windows
      name: Win64 VC2017 Vk1.0
      language: cpp
      script:
        - mkdir -p build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -T v141 -DAE_CI_BUILD=ON -DAE_CI_TYPE=1 -DAE_VULKAN_VERSION="100" .. 
        - cmake --build . --config Release
        - ctest -C Release --verbose
    
    # Windows MSVC x64 Vulkan 1.1
    - os: windows
      name: Win64 VC2017 Vk1.1
      language: cpp
      script:
        - mkdir -p build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -T v141 -DAE_CI_BUILD=ON -DAE_CI_TYPE=1 -DAE_VULKAN_VERSION="110" .. 
        - cmake --build . --config Release
        - ctest -C Release --verbose

    # Windows MSVC x64 Vulkan 1.2
    - os: windows
      name: Win64 VC2017 Vk1.2
      language: cpp
      script:
        - mkdir -p build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" -T v141 -DAE_CI_BUILD=ON -DAE_CI_TYPE=1 -DAE_VULKAN_VERSION="120" .. 
        - cmake --build . --config Release
        - ctest -C Release --verbose

    #- os: windows
    #  name: Win64 VC2019
    #  language: cpp
    #  script:
    #    - mkdir -p build
    #    - cd build
    #    - cmake -G "Visual Studio 16 2019" -A Win64 -DAE_CI_BUILD=ON -DAE_CI_TYPE=1 .. 
    #    - cmake --build . --config Release
    #    - ctest -C Release --verbose
        
    # Android
    # from https://github.com/android/ndk-samples/blob/master/.travis.yml
    - os: android
      name: android
      language: android
      sudo: true
      android:
        components:
            - tools
            - platform-tools
            - extra-google-m2repository
            - extra-android-m2repository
      addons:
        apt_packages:
            - pandoc
        
      before_install:
        - sudo apt-get install ant

      install:
        - echo y | sdkmanager "ndk-bundle"
        - echo y | sdkmanager "cmake;3.6.4111459"
        - echo y | sdkmanager --channel=3 --channel=1 "cmake;3.10.2.4988404"
        - echo y | sdkmanager "lldb;3.1"
      
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle

      script:
        - cd ./android
        - chmod +x gradlew
        - ./gradlew build
