
include( ExternalProject )

ExternalProject_Add( "ResourcePacker"
		LOG_OUTPUT_ON_FAILURE 1
		LIST_SEPARATOR		"|"
		DOWNLOAD_COMMAND	""
		# configure
		SOURCE_DIR			"${CMAKE_CURRENT_SOURCE_DIR}/engine_tools/res_pack"
		CMAKE_GENERATOR		"${CMAKE_GENERATOR}"
		CMAKE_GENERATOR_PLATFORM "${CMAKE_GENERATOR_PLATFORM}"
		CMAKE_GENERATOR_TOOLSET	"${CMAKE_GENERATOR_TOOLSET}"
		CMAKE_ARGS			"-DCMAKE_CONFIGURATION_TYPES=Release"
							"-DCMAKE_BUILD_TYPE=Release"
							"-DAE_ENABLE_TESTS=OFF"
							"-DAE_ORIGIN_SOURCE_PATH=${CMAKE_SOURCE_DIR}"
							"-DAE_TARGET_BINARY_PATH=${MAIN_BINARY_DIR}"
		LOG_CONFIGURE 		1
		# build
		BINARY_DIR			"${CMAKE_CURRENT_BINARY_DIR}/build-ResourcePacker"
		BUILD_COMMAND		"${CMAKE_COMMAND}"
							--build .
							--config Release
		LOG_BUILD 			1
		# install
		INSTALL_DIR 		""
		INSTALL_COMMAND		""
		# test
		TEST_COMMAND 		""
	)
set_property( TARGET "ResourcePacker" PROPERTY FOLDER "EngineTools" )

if (NOT ANDROID)
	set( AE_PIPELINE_COMPILER_LIBRARY "${MAIN_BINARY_DIR}/Release/PipelineCompiler${CMAKE_SHARED_LIBRARY_SUFFIX}" CACHE INTERNAL "" FORCE )
	set( AE_SAMPLER_PACKER_LIBRARY "${MAIN_BINARY_DIR}/Release/SamplerPacker${CMAKE_SHARED_LIBRARY_SUFFIX}" CACHE INTERNAL "" FORCE )
endif ()
