# setup build on CI

if (AE_CI_BUILD)
	message( STATUS "configured CI build" )
	
	set( AE_ENABLE_TESTS ON CACHE INTERNAL "" FORCE )
	set( AE_ENABLE_SIMPLE_COMPILER_OPTIONS ON CACHE INTERNAL "" FORCE )
	set( AE_ENABLE_ANGELSCRIPT ON CACHE INTERNAL "" FORCE )
	set( AE_EXTERNALS_USE_STABLE_VERSIONS ON CACHE INTERNAL "" FORCE )

	if (WIN32 AND MSVC)
		set( AE_EXTERNALS_USE_PREBUILD ON CACHE INTERNAL "" FORCE )
	else ()
		set( AE_EXTERNALS_USE_PREBUILD OFF CACHE INTERNAL "" FORCE )
	endif ()

endif ()
